---
when:
  event: [tag, release]
steps:
  publish:
    image: rust@sha256:5474dce321a62be62d86355e776a035587345eb385e049760cfb6b04b6fa9025
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands: [cargo publish]
