---
when:
  event: [tag, release]
steps:
  publish:
    image: rust@sha256:910b9dc6597a3ef16458dc1d20520714d3526ddb038749b8d87334798064d672
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands: [cargo publish]
