when:
  event:
    - tag

steps:
  - image: rust
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands:
      - cargo publish