---
when:
  event: [tag, release]
steps:
  publish:
    image: rust@sha256:a2d7edb8d58e216f3c81ce2d9704ddf00d6b3fd2d55039be9f90ed8b62d8bb3b
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands: [cargo publish]
