---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  lint:
    image: rust@sha256:ad8c72c693b517ed60c930839daed91a5696fa6118f031d888cd0b7055a921a3
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo check
