---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  lint:
    image: rust@sha256:638747aac515b4b346c144d8f8debfc367e3a89ba62383df72a184c4b9e31313
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo check
