---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  lint:
    image: rust@sha256:5474dce321a62be62d86355e776a035587345eb385e049760cfb6b04b6fa9025
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo check
