when:
  event: [push, pull_request]
  branch:
    exclude:
      - main

matrix:
  RUST: [stable, beta, nightly]

steps:
  lint:
    image: rust
    entrypoint: ["/bin/bash", "-c", "echo $CI_SCRIPT | base64 -d | /bin/bash -e"]
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo check

  test:
    image: rust
    entrypoint: ["/bin/bash", "-c", "echo $CI_SCRIPT | base64 -d | /bin/bash -e"]
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - cargo test

  audit:
    image: woodpeckerci/plugin-trivy
    commands:
      - trivy fs .
