clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0
      git-user-name: Solace System Renovate Fox [bot]
      git-user-email: renovate@solace-system.co.uk
      tags: true
      ssh-key:
        from_secret: GIT_PRIVATE_KEY

runs_on:
  - success

when:
  event:
    - push
  branch:
    include:
      - main

steps:
  release:
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - cargo install cargo-binstall
      - cargo binstall --locked cargo-edit
      - cargo binstall --locked cocogitto
      - git config user.name "Solace System Renovate Fox [bot]"
      - git config user.email renovate@solace-system.co.uk
      - cog bump --auto

  push:
    image: appleboy/drone-git-push
    settings:
      branch: main
      followtags: true
      ssh_key:
        from_secret: GIT_PRIVATE_KEY

depends_on:
  - test