clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

when:
  event:
    - push
  branch:
    include:
      - main

steps:
  release:
    image: rust
    environment:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRY_TOKEN:
        from_secret: CARGO_REGISTRY_TOKEN
    commands:
      - rustup default $RUST
      - cargo install cargo-binstall
      - cargo binstall --locked cargo-edit
      - cargo binstall --locked cocogitto
      - cog bump --auto

  push:
    image: appleboy/drone-git-push
    settings:
      branch: main
      followtags: true

depends_on:
  - test