clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0
      git-user-name: Solace System Renovate Fox [bot]
      git-user-email: renovate@solace-system.co.uk
      tags: true

runs_on:
  - success

when:
  event:
    - push
  branch:
    include:
      - main

steps:
  release:
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default stable
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall --locked cargo-edit
      - cargo binstall --locked cocogitto
      - git config user.name "Solace System Renovate Fox [bot]"
      - git config user.email renovate@solace-system.co.uk
      - cog bump --auto
  push:
    depends_on:
      - release
    image: appleboy/drone-git-push
    settings:
      remote: ssh://git@codeberg.org/PurpleBooth/anarchist-readable-name-generator-lib.git
      branch: main
      followtags: true
      ssh_key:
        from_secret: GIT_PRIVATE_KEY

depends_on:
  - test
  - lint
