
when:
  event:
    - push
  branch:
    include:
      - main

steps:
  clone:
    image: woodpeckerci/plugin-git
    settings:
      depth: -1          # full clone
      partial: false     # make sure we don’t do a blobless checkout

  release:
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - cargo install cargo-binstall
      - cargo binstall --locked cocogitto
      - cog bump --auto

  push:
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: main
      local_ref: main

depends_on:
  - test