---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  test:
    image: rust@sha256:910b9dc6597a3ef16458dc1d20520714d3526ddb038749b8d87334798064d672
    environment:
      CARGO_TERM_COLOR: always
    commands: [rustup default $RUST, cargo test]
  audit:
    image: woodpeckerci/plugin-trivy@sha256:dabf299830ab93a01581211c1fa47dbadb9b899892d87b7cf7949e544ad64f52
    commands: [trivy fs .]
