---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  test:
    image: rust@sha256:a2d7edb8d58e216f3c81ce2d9704ddf00d6b3fd2d55039be9f90ed8b62d8bb3b
    environment:
      CARGO_TERM_COLOR: always
    commands: [rustup default $RUST, cargo test]
  audit:
    image: woodpeckerci/plugin-trivy@sha256:612038a5ca2d46fd34bb22510ce84f5ce9b605f36304e58faca8ff3edac59eed
    commands: [trivy fs .]
