---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  test:
    image: rust@sha256:80302520b7199f0504975bca59a914015e9fee088f759875dbbc238ca9509ee1
    environment:
      CARGO_TERM_COLOR: always
    commands: [rustup default $RUST, cargo test]
  audit:
    image: woodpeckerci/plugin-trivy@sha256:da92938a2832f2f0c0cf29ac4cb8c072fa4191448c06ae84a2fcd18e5f5fc611
    commands: [trivy fs .]
