---
when:
  event: [push, pull_request]
  path:
    exclude: [CHANGELOG.md]
matrix:
  RUST: [stable, beta, nightly]
steps:
  test:
    image: rust@sha256:65734d21f103d104fe0d9e508a424f7f60abd10e489d36de8bd36ae6c80e746d
    environment:
      CARGO_TERM_COLOR: always
    commands: [rustup default $RUST, cargo test]
  audit:
    image: woodpeckerci/plugin-trivy@sha256:da92938a2832f2f0c0cf29ac4cb8c072fa4191448c06ae84a2fcd18e5f5fc611
    commands: [trivy fs .]
