matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    when:
      event: [push, pull_request]
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo check
      - cargo test

  audit:
    when:
      event: [ push, pull_request ]
    image: woodpeckerci/plugin-trivy
    commands:
      - trivy fs .